language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
      env: SYMFONY_VERSION=3.3.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - wget http://getcomposer.org/composer.phar
  - if [ "$SYMFONY_VERSION" != "" ]; then php -d memory_limit=-1 composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update; fi;

install: php -d memory_limit=-1 composer.phar install --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text